ARG BASE=alpine:3.11
FROM ${BASE}
RUN apk add --update --no-cache build-base git gcc cmake make linux-headers yaml-dev libmicrohttpd-dev curl-dev util-linux-dev ncurses-dev

COPY scripts /device-bacnet-c/scripts
COPY src /device-bacnet-c/src/
COPY VERSION /device-bacnet-c/

WORKDIR /device-bacnet-c

RUN /device-bacnet-c/scripts/build_deps.sh

RUN /device-bacnet-c/scripts/build.sh
