ARG BASE=alpine:3.11
FROM ${BASE} as builder
RUN apk add --update --no-cache build-base git gcc cmake make linux-headers yaml-dev libmicrohttpd-dev curl-dev util-linux-dev ncurses-dev

COPY scripts /device-bacnet-c/scripts
COPY src /device-bacnet-c/src/
COPY VERSION /device-bacnet-c/

WORKDIR /device-bacnet-c

RUN /device-bacnet-c/scripts/build_deps.sh

RUN /device-bacnet-c/scripts/build.sh 

FROM alpine:3.11
MAINTAINER iotech <support@iotechsys.com>
RUN apk add --update --no-cache linux-headers yaml libmicrohttpd curl libuuid

COPY --from=builder /device-bacnet-c/build/release/ /
COPY --from=builder /usr/lib/libcsdk.so /usr/lib
COPY --from=builder /usr/include/edgex /usr/include/edgex
COPY --from=builder /usr/include/iot /usr/include/iot
COPY --from=builder /usr/share/doc/edgex-csdk /usr/share/doc/edgex-csdk
COPY --from=builder /usr/local/lib/libcbor* /usr/local/lib/

COPY scripts/startup.sh /startup.sh
COPY LICENSE /.
COPY Attribution.txt /.
COPY res /res
COPY profiles /profiles

LABEL license='SPDX-License-Identifier: Apache-2.0' \
      copyright='Copyright (c) 2019-2020: IoTech Ltd'

ENTRYPOINT ["/startup.sh"]
